export interface ThemeHighlights {
  background: string;
  text: string;
  variable: string;
  attribute: string;
  definition: string;
  keyword: string;
  operator: string;
  property: string;
  number: string;
  string: string;
  comment: string;
  meta: string;
  tag?: string;
  variable2?: string;
  variable3?: string;
  /** Bracket-pair colors (VS Code style), cycled by nesting depth. */
  brackets?: string[];
}

export interface Theme {
  id: string;
  name: string;
  light?: boolean;
  highlights: ThemeHighlights;
}

export const THEMES: Theme[] = [
  {
    id: 'dark-modern',
    name: 'Dark Modern',
    highlights: {
      // VS Code Default Dark Modern (semantic-token inspired)
      // control: #C586C0 · keyword/type-kw: #569CD6 · type: #4EC9B0
      // function: #DCDCAA · variable: #9CDCFE · string: #CE9178
      background: '#1F1F1F',
      text: '#D4D4D4',
      variable: '#9CDCFE',
      variable2: '#4FC1FF',
      variable3: '#4EC9B0',
      attribute: '#9CDCFE',
      definition: '#DCDCAA',
      keyword: '#C586C0',
      operator: '#D4D4D4',
      property: '#9CDCFE',
      number: '#B5CEA8',
      string: '#CE9178',
      comment: '#6A9955',
      meta: '#569CD6',
      tag: '#569CD6',
      // VS Code editorBracketHighlight.foreground1..3
      brackets: ['#FFD700', '#DA70D6', '#179FFF'],
    },
  },
  {
    id: 'seti',
    name: 'Seti',
    highlights: {
      background: '#151718',
      text: '#CFD2D1',
      variable: '#55b5db',
      variable2: '#a074c4',
      variable3: '#9fca56',
      attribute: '#9fca56',
      definition: '#55b5db',
      keyword: '#e6cd69',
      operator: '#9fca56',
      property: '#a074c4',
      number: '#cd3f45',
      string: '#55b5db',
      comment: '#41535b',
      meta: '#55b5db',
      tag: '#55b5db',
    },
  },
  {
    id: 'dracula',
    name: 'Dracula',
    highlights: {
      background: '#282a36',
      text: '#f8f8f2',
      variable: '#50fa7b',
      variable2: 'white',
      variable3: '#ffb86c',
      attribute: '#50fa7b',
      definition: '#50fa7b',
      keyword: '#ff79c6',
      operator: '#ff79c6',
      property: '#66d9ef',
      number: '#bd93f9',
      string: '#f1fa8c',
      comment: '#6272a4',
      meta: '#f8f8f2',
      tag: '#ff79c6',
    },
  },
  {
    id: 'monokai',
    name: 'Monokai',
    highlights: {
      background: '#272822',
      text: '#f8f8f2',
      variable: '#f8f8f2',
      variable2: '#9effff',
      variable3: '#66d9ef',
      attribute: '#a6e22e',
      definition: '#fd971f',
      keyword: '#f92672',
      operator: '#fff',
      property: '#a6e22e',
      number: '#ae81ff',
      string: '#e6db74',
      comment: '#75715e',
      meta: '#555',
      tag: '#bc6283',
    },
  },
  {
    id: 'one-dark',
    name: 'One Dark',
    highlights: {
      background: '#282c34',
      text: '#abb2bf',
      variable: '#e06c75',
      attribute: '#d19a66',
      definition: '#e5c07b',
      keyword: '#c678dd',
      operator: '#56b6c2',
      property: '#56b6c2',
      number: '#d19a66',
      string: '#98c379',
      comment: '#5c6370',
      meta: '#abb2bf',
      tag: '#e06c75',
    },
  },
  {
    id: 'one-light',
    name: 'One Light',
    light: true,
    highlights: {
      background: '#fafafa',
      text: '#383a42',
      variable: '#e06c75',
      variable2: '#e45649',
      attribute: '#d19a66',
      definition: '#4078f2',
      keyword: '#a626a4',
      operator: '#0184bc',
      property: '#4078f2',
      number: '#986801',
      string: '#50a14f',
      comment: '#a0a1a7',
      meta: '#383a42',
      tag: '#e45649',
    },
  },
  {
    id: 'night-owl',
    name: 'Night Owl',
    highlights: {
      background: '#011627',
      text: '#abb2bf',
      variable: '#82AAFF',
      attribute: '#F78C6C',
      definition: '#82AAFF',
      keyword: '#c792ea',
      operator: '#c792ea',
      property: '#fff',
      number: '#F78C6C',
      string: '#ecc48d',
      comment: '#5c6370',
      meta: '#7fdbca',
      tag: '#7fdbca',
    },
  },
  {
    id: 'nord',
    name: 'Nord',
    highlights: {
      background: '#2e3440',
      text: '#d8dee9',
      variable: '#88C0D0',
      variable3: '#d8dee9',
      attribute: '#8FBCBB',
      definition: '#D8DEE9',
      keyword: '#81A1C1',
      operator: '#81A1C1',
      property: '#D8DEE9',
      number: '#B48EAD',
      string: '#A3BE8C',
      comment: '#4C566A',
      meta: '#81A1C1',
      tag: '#81A1C1',
    },
  },
  {
    id: 'material',
    name: 'Material',
    highlights: {
      background: '#263238',
      text: 'rgba(233, 237, 237, 1)',
      variable: '#82B1FF',
      variable2: '#80CBC4',
      variable3: '#DECB6B',
      attribute: '#FFCB6B',
      definition: 'rgba(233, 237, 237, 1)',
      keyword: 'rgba(199, 146, 234, 1)',
      operator: 'rgba(233, 237, 237, 1)',
      property: '#80CBAE',
      number: '#F77669',
      string: '#C3E88D',
      comment: '#546E7A',
      meta: '#80CBC4',
      tag: 'rgba(255, 83, 112, 1)',
    },
  },
  {
    id: 'vscode',
    name: 'VSCode',
    highlights: {
      background: '#1E1E1E',
      text: '#D4D4D4',
      variable: '#9CDCFE',
      attribute: '#d19a66',
      definition: '#DCDCAA',
      keyword: '#C586C0',
      operator: '#D4D4D4',
      property: '#DCDCAA',
      number: '#B5CEA8',
      string: '#CE9178',
      comment: '#6A9955',
      meta: '#D4D4D4',
      tag: '#569cd6',
    },
  },
  {
    id: 'solarized dark',
    name: 'Solarized (Dark)',
    highlights: {
      background: '#002b36',
      text: '#839496',
      variable: '#839496',
      variable2: '#b58900',
      variable3: '#6c71c4',
      attribute: '#2aa198',
      definition: '#2aa198',
      keyword: '#cb4b16',
      operator: '#6c71c4',
      property: '#2aa198',
      number: '#d33682',
      string: '#859900',
      comment: '#586e75',
      meta: '#859900',
      tag: '#93a1a1',
    },
  },
  {
    id: 'solarized light',
    name: 'Solarized (Light)',
    light: true,
    highlights: {
      background: '#fdf6e3',
      text: '#657b83',
      variable: '#839496',
      variable2: '#b58900',
      variable3: '#6c71c4',
      attribute: '#2aa198',
      definition: '#2aa198',
      keyword: '#cb4b16',
      operator: '#6c71c4',
      property: '#2aa198',
      number: '#d33682',
      string: '#859900',
      comment: '#586e75',
      meta: '#859900',
      tag: '#93a1a1',
    },
  },
  {
    id: 'synthwave-84',
    name: "SynthWave '84",
    highlights: {
      background: '#2b213a',
      text: '#b6b1b1',
      variable: '#f92aad',
      attribute: '#fff5f6',
      definition: '#fdfdfd',
      keyword: '#f4eee4',
      operator: '#f4eee4',
      property: '#fdfdfd',
      number: '#f97e72',
      string: '#ff8b39',
      comment: '#6d77b3',
      meta: '#ff8b39',
      tag: '#f92aad',
    },
  },
  {
    id: 'shades-of-purple',
    name: 'Shades of Purple',
    highlights: {
      background: '#2D2B55',
      text: '#FFFFFF',
      variable: '#9EFFFF',
      attribute: '#9EFFFF',
      definition: '#9EFFFF',
      keyword: '#FF9D00',
      operator: '#FF9D00',
      property: '#FAD000',
      number: '#FF628C',
      string: '#A5FF90',
      comment: '#B362FF',
      meta: '#FF9D00',
      tag: '#9EFFFF',
    },
  },
  {
    id: 'cobalt',
    name: 'Cobalt',
    highlights: {
      background: '#002240',
      text: '#fff',
      variable: '#9effff',
      variable3: 'white',
      attribute: '#ff80e1',
      definition: '#fff',
      keyword: '#ffee80',
      operator: '#fff',
      property: '#fff',
      number: '#ff80e1',
      string: '#3ad900',
      comment: '#08f',
      meta: '#ff9d00',
      tag: '#9effff',
    },
  },
  {
    id: 'panda-syntax',
    name: 'Panda',
    highlights: {
      background: '#292A2B',
      text: '#E6E6E6',
      variable: '#ffb86c',
      variable2: '#ff9ac1',
      variable3: '#ff9ac1',
      attribute: '#ffb86c',
      definition: '#e6e6e6',
      keyword: '#FF75B5',
      operator: '#f3f3f3',
      property: '#f3f3f3',
      number: '#FFB86C',
      string: '#19F9D8',
      comment: '#676B79',
      meta: '#b084eb',
      tag: '#ff2c6d',
    },
  },
  {
    id: 'zenburn',
    name: 'Zenburn',
    highlights: {
      background: '#3f3f3f',
      text: '#dcdccc',
      variable: '#dfaf8f',
      variable3: '#dcdccc',
      attribute: '#dfaf8f',
      definition: '#dcdccc',
      keyword: '#f0dfaf',
      operator: '#f0efd0',
      property: '#dfaf8f',
      number: '#dcdccc',
      string: '#cc9393',
      comment: '#7f9f7f',
      meta: '#f0dfaf',
      tag: '#93e0e3',
    },
  },
];

export const THEMES_MAP = Object.fromEntries(THEMES.map((t) => [t.id, t]));

export const FONTS = [
  'editor',
  'Hack',
  'Fira Code',
  'JetBrains Mono',
  'Source Code Pro',
  'Cascadia Code',
  'IBM Plex Mono',
  'Inconsolata',
  'Ubuntu Mono',
  'Anonymous Pro',
  'Droid Sans Mono',
  'Space Mono',
  'Monoid',
  'Fantasque Sans Mono',
  'Menlo',
  'Monaco',
  'Consolas',
  'monospace',
];

export function getTheme(id: string): Theme {
  return THEMES_MAP[id] ?? THEMES_MAP['dark-modern'];
}


